// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATCrzoCw_5YmFHXA_zzMdMxTKHt5nNAOw',
    appId: '1:314909974489:web:5c79a574bb8825464583c8',
    messagingSenderId: '314909974489',
    projectId: 'fcm4flutter-57cd2',
    authDomain: 'fcm4flutter-57cd2.firebaseapp.com',
    storageBucket: 'fcm4flutter-57cd2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA95Mfmtocb_J3ezgzUvo3xoCcdNI3HHvs',
    appId: '1:314909974489:android:e5f8e26b6eb5cd524583c8',
    messagingSenderId: '314909974489',
    projectId: 'fcm4flutter-57cd2',
    storageBucket: 'fcm4flutter-57cd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtfOlJJ4RmJnDqTzkeAlsni-7g2R-mfrY',
    appId: '1:314909974489:ios:98aee3cea54e0f3a4583c8',
    messagingSenderId: '314909974489',
    projectId: 'fcm4flutter-57cd2',
    storageBucket: 'fcm4flutter-57cd2.appspot.com',
    iosBundleId: 'com.example.flutterTicketsBookingAgency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtfOlJJ4RmJnDqTzkeAlsni-7g2R-mfrY',
    appId: '1:314909974489:ios:98aee3cea54e0f3a4583c8',
    messagingSenderId: '314909974489',
    projectId: 'fcm4flutter-57cd2',
    storageBucket: 'fcm4flutter-57cd2.appspot.com',
    iosBundleId: 'com.example.flutterTicketsBookingAgency',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATCrzoCw_5YmFHXA_zzMdMxTKHt5nNAOw',
    appId: '1:314909974489:web:a4198c5a4717c0b14583c8',
    messagingSenderId: '314909974489',
    projectId: 'fcm4flutter-57cd2',
    authDomain: 'fcm4flutter-57cd2.firebaseapp.com',
    storageBucket: 'fcm4flutter-57cd2.appspot.com',
  );
}
